name: PYPI build and publish
uses: etils-actions/pypi-build-publish@v1

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip
      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Install dependencies
        run: python3 -m pip install -r ./src/gapy/requirements.txt

      - use: conchylicultor/pypi-build-publish@v1
        with:
          pypi-token: ${{ secrets.PYPI_API_TOKEN }}